name: Upgrade build systems

on:
  workflow_dispatch:

jobs:
  buildscript-maintenance:
    if: contains('["Dream-Master","mitchej123","Dream-Master",]', github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup git user
        run: |
          git config user.name "GitHub CI Bot"
          git config user.email "<>"
          git config --global url."https://api:$TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$TOKENN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$TOKEN@github.com/".insteadOf "git@github.com:"
        env:
          TOKEN: ${{ secrets.TOKEN_PUSH_TO_PROTECTED_BRANCHES }}

      - name: Ensure build script version is up to date
        run: ./upgrade-all.sh
